### ISSUE TITLE
Display Age along with Date-of-Birth.

### ISSUE THREAD

**Issue by kfogel** [hmis-tools/hmis-api-demo-client#1]
(This is regarding the `intake-ui-demo` branch, as of commit 488472c1.)

Even though we show Date-of-Birth for each possible match (in the autofill dropdown list), it's useful to show Age right next to it.  Even though Age can of course be calculated from DoB, in practice, for the person doing the client intake on-the-spot, it's convenient to see the age right there on the screen.

**Comment by nttaylor** [comment]
Fixed following 06620ce
