### ISSUE TITLE
Display dates in "NN MON YYYY" format, e.g., "06 July 1968".

### ISSUE THREAD

**Issue by kfogel** [hmis-tools/hmis-api-demo-client#2]
(This is regarding the `intake-ui-demo` branch, as of commit 488472c1.)

Let's display Date-of-Birth like "06 Jul 1968".  This is easier for the human eye to parse, and there is no ambiguity about month.

I think this would generally apply to other dates too, but we should evaluate on a case-by-case basis.  For now, Date-of-Birth is the only date displayed, so it's the only date to which this issue is relevant.

**Comment by nttaylor** [comment]
Fixed following 06620ce
