### ISSUE TITLE
Data is cached; manual data changes are not immediately reflected via API

### ISSUE THREAD

**Issue by cecilia-donnelly** [hmis-tools/hmis-api-demo-client#20]
Database changes require a `mvn tomcat7:redeploy` to be reflected via the API.  This is especially noticeable when testing: neither loading the sample data nor manually deleting clients from the table are immediately reflected in responses to API calls.  You can see this in direct calls to the Java endpoints (e.g. localhost:8080/openhmis/services/clients) and indirect calls from the Node endpoints (e.g. localhost:3000/clients).

**Comment by kfogel** [comment]
Hmm.  Does this mean that even data entered via a client app is not visible in the database?  Like if we created a new Client record via the UI, or created many of them via import, the new records would not be visible in the database immediately to both that client app and any others that make API calls?

**Comment by kfogel** [comment]
Also, is this related to issue #17?

**Comment by cecilia-donnelly** [comment]
No.  Changes made via the app are reflected immediately in the database (and in the app).  #17 seems unrelated.  I just added a reload to fix that one.  We talked about this issue with @slifty in IRC a bit:

```
Jul 30 16:07:31 <kfogel>    cdonnelly: imported the data, but http://localhost:8080/openhmis/services/clients still shows empty brackets
Jul 30 16:07:58 <cdonnelly> kfogel: I think I tried redeploying afterward?  It might just take a couple minutes
Jul 30 16:08:42 <kfogel>    cdonnelly: ok
Jul 30 16:08:52 <slifty>    cdonnelly: shouldn't have any effect
Jul 30 16:09:28 <slifty>    cdonnelly: that said, maybe there's some weird caching thing with hibernate that needs fixing... idk
Jul 30 16:10:04 <cdonnelly> slifty: *shrug*
Jul 30 16:10:46 <cdonnelly> slifty: the same thing happened to me (still had empty brackets after running scripts)
Jul 30 16:10:53 <slifty>    cdonnelly: I know
Jul 30 16:11:07 <slifty>    cdonnelly: but the brackets showing means there isn't a DB connection error
Jul 30 16:11:10 <cdonnelly> slifty: right
Jul 30 16:11:52 <kfogel>    cdonnelly, slifty: I did maven redeploy and suddenly the data was there.
```

As far as I can tell, this issue is exclusively about changes made _directly to the db_ not being visible immediately via the API, without doing a `mvn tomcat7:redeploy`.  I'm not sure how long it would take for them to be populated without doing that redeploy.

**Comment by cecilia-donnelly** [comment]
@kfogel: This issue might be better placed in the OpenHMIS repo, actually.  I don't think it has anything to do with the client app.

**Comment by cecilia-donnelly** [comment]
See https://github.com/PCNI/OpenHMIS/issues/30.  No need to have this here, since it doesn't really have to do with our app.
