### ISSUE TITLE
Put a label on unique ID, in autofill dropdown.

### ISSUE THREAD

**Issue by kfogel** [hmis-tools/hmis-api-demo-client#3]
(This is regarding the `intake-ui-demo` branch, as of commit 488472c1.)

I assume the digital-fingerprint codes being displayed (e.g., "0171bb3b" for "Stein N. Miranda") displaying that person's unique client key within, say, the Pathways system?

If so, let's give that field a label, say, "CID" (which could be "Client ID" or "COMPASS ID" -- let us savor the ambiguity.   So, e.g, `CID: 0171bb3b`.

**Comment by nttaylor** [comment]
Fixed following 06620ce
