### ISSUE TITLE
Display identity of authenticated user.

### ISSUE THREAD

**Issue by kfogel** [hmis-tools/hmis-api-demo-client#36]
The user should see whom they're logged in as, at the top of the client -- especially since Google authentication happens so fast that one might not know which account one got logged in as.

Since the client doesn't have the actual Google email address locally, it will have to request it from the server (the HMIS server, that is, though perhaps the request will be ferried by the in-between server that is part of the client).

**Comment by cecilia-donnelly** [comment]
Done and deployed as of [2016-07-25].
