### ISSUE TITLE
Ensure "Add New Client" button is visible, perhaps by putting at top.

### ISSUE THREAD

**Issue by kfogel** [hmis-tools/hmis-api-demo-client#6]
The "Add New Client" button (whether active or grayed out) is at the bottom of the UI for me, and by default is scrolled off the bottom of the screen in my standard Firefox size.  That means that when I narrow things down to zero matches, what I'm looking at is some string that I've typed in the top field, then below that a tall blank area containing (as expected) no matches, and then -- if I scroll down in my browser window! -- an "Add New Client" button.

If the "Add New Client" were up at the top, then it would be easy to reach, eye-wise and hand-wise (maybe even by TAB-ing over?) from the text entry field.

But because we don't want to waste vertical space, that implies, I think, putting it to the _right_ of the text entry field?  What do you think?

Mainly, I want to ensure the user doesn't have to ever scroll and doesn't face the risk of the "Add New Client" button being not visible on the screen by default.  It doesn't have to be the above solution, though.

**Comment by cecilia-donnelly** [comment]
@kfogel and I talked and decided to close this for now.
