### ISSUE TITLE
Feedback on 1st video, from Dave Totten.

### ISSUE THREAD

**Issue by kfogel** [hmis-tools/hmis-api-demo-client#7]
This issue is just a list of feedback for @nttaylor, from my phone conversation with Dave Totten yesterday after he saw the demo.  Much of this is just about using terminology and fields that are already familiar to people who have HMIS experience.
- [x] Don't show "CID" field anywhere
- [x] Also, if we were showing it, the standard label would be "Personal ID", not "CID" anyway.  But we're not showing it, so that doesn't matter here; it's just something to know for next time.
- [x] Use the real "OpenHMIS" logo, the one from http://openhmis.org/.
- [x] Don't have any address fields.  Those aren't necessary, and they're not part of the HUD standard anyway (at least not part of the Universal Data Elements portion).
- [x] The fields we should have are: "Last", "First", "SSN", "DoB", "Gender", "Ethnicity", "Race".  They should have exactly those names.  (I'll check with the HUD standards and COMPASS on that, but for now, use those names.  They are much closer to, if not exactly, what the HUD-standard field names are.)
- [x] Add narration to explain what's going on at each step.  Yes, I realize this is a big item :-), but it's necessary.  In particular, when clicking on the inactive "Add New Client" button, narrate the fact that the button has no effect because there is still at least one matching Client in the results list, and so to avoid the risk of creating a duplicate record, we do not even allow the possibility of creating a new client.  The narration should also explain how the narrow-down search effect works on the front page.  Dave agreed it is a good interface, but says that behavior will not be obvious to all newcomer observers, and that we need to explain what's going on so they understand.  In general, don't feel shy about narrating a thing that might seem obvious.  We should be telling the audience exactly what's going on at every step.
- [x] We should put the next video on YouTube, where there are standard controls to play, pause, etc.  (Apparently, not all browsers offer these when one plays a video file directly in the browser.)  That part is for me to do and I will do it; I'm just noting it here.
- [x] For DoB, use a calendar-popup interface element (you know the kind I mean), though still allow typing a date if the person wants to do that.
- [x] Both "Ethnicity" and "Gender" (and maybe "Race"? need to check) should offer dropdowns, and the dropdowns should offer the exact lists of choices taken from the HUD data standards.  I don't have the link to those standards handy right here -- I can try to find it later, but you may be able to get there quickly by starting at https://github.com/PCNI/OpenHMIS/blob/master/API.md and following the links to "HMIS Data Exchange Resources", or maybe "HUD 2014 HMIS Data Dictionary".  Dan Schultz may also have quick access to those lists of choices.

**Comment by nttaylor** [comment]
Just to confirm a few things:
1. Should this continue to be my priority over smoke alarm and swoptact? I
   am assuming that it is for now.
2. You mentioned that the fields we should have are: "Last", "First",
   "SSN", "DoB", "Gender", "Ethnicity", "Race".  Do I understand correctly
   that these are the _only_ fields we should have? No middle initial? No
   homelessness status?
3. Also, are all of the above fields required?
4. You want to let the person _type_ a date for DOB? Would it not be
   acceptable to do this with dropdowns (as well as the widget)? Parsing out
   "January 1", "Jan 1", "Kanuary 1", "1/1", "01/1" etc. would introduce lots
   of problems.
5. Narration is easy to do :-)
6. Are the options for ethnicity and race not those given in the
   questionnaire in the repository at
   openhmis-intake/docs/2015-Client-Intake-Form.pdf? This is what I based the
   intake form on that is currently in the demo.

Let me know what you think.

N

**Comment by kfogel** [comment]
On Jul 22, 2015 9:32 AM, "nttaylor" notifications@github.com wrote:

> Just to confirm a few things:
> 1. Should this continue to be my priority over smoke alarm and swoptact? I
>    am assuming that it is for now.

Yes, please.

> 1. You mentioned that the fields we should have are: "Last", "First",
>    "SSN", "DoB", "Gender", "Ethnicity", "Race". Do I understand correctly
>    that these are the _only_ fields we should have? No middle initial? No
>    homelessness status?

Yup.

> 1. Also, are all of the above fields required?

Yes.

> 1. You want to let the person _type_ a date for DOB? Would it not be
>    acceptable to do this with dropdowns (as well as the widget)? Parsing out
>    "January 1", "Jan 1", "Kanuary 1", "1/1", "01/1" etc. would introduce lots
>    of problems.

Dropdowns in addition to calendar pop-up is fine, esp since dropdowns
support typing too.

> 1. Narration is easy to do :-)

See, this is the secret weapon our web designer has :-).

> 1. Are the options for ethnicity and race not those given in the
>    questionnaire in the repository at
>    openhmis-intake/docs/2015-Client-Intake-Form.pdf? This is what I based the
>    intake form on that is currently in the demo.

Those are probably right.  Use them for now; I'll do a little research.
It'll be simple to change if we need to.

Best,
-K

**Comment by cecilia-donnelly** [comment]
@nttaylor, some questions based on looking at the site and the criteria above:

> The fields we should have are: "Last", "First", "SSN", "DoB", "Gender", "Ethnicity", "Race". They should have exactly those names. 

We currently don't have labels on "Last," "First," and "DoB."  Should we?

> For DoB, use a calendar-popup interface element (you know the kind I mean), though still allow typing a date if the person wants to do that.

I like the calendar!  However, we're not currently allowing typing in the date.  Did you and @kfogel talk about this and decide against typing in dates?  I _really_ like the click-to-change-month-and-year functionality!

Finally, did you and @kfogel talk about the race/ethnicity options?

**Comment by cecilia-donnelly** [comment]
Thanks to @slifty, we know that we need to change the race and ethnicity dropdowns to match the values provided by the API:

NON_HISPANIC (104, "Non-Hispanic/Non-Latino"),
HISPANIC (105, "Hispanic/Latino"),
UNKNOWN (8, "Client doesn't know"),
REFUSED (9, "Client Refused")

ASIAN (5, "Asian"),
BLACK (6, "Black or African American"),
INDIAN (7, "American Indian or Alaska Native"),
WHITE (8, "White"),
HAWAIIAN (9, "Native Hawaiian or Other Pacific Islander"),
OTHER (14, "Other"),
UNKNOWN (15, "Client doesn't know"),
REFUSED (16, "Client Refused");

@nttaylor is changing these options and adding labels as mentioned above.  We'll forgo the typed-in date until the next iteration.

**Comment by cecilia-donnelly** [comment]
@nttaylor added narration and @kfogel put this on YouTube, so we're done here.
