### ISSUE TITLE
"back to results" behavior should be changed

### ISSUE THREAD

**Issue by nttaylor** [hmis-tools/hmis-api-demo-client#9]
Currently, the intake form has two buttons, which are always active: "back to results" (which returns the user to the search results page that brought them to the intake form) and "save changes" (which saves any changes to the old or new client being worked on).

If the user enters changes into the intake form and then clicks "back to results", the changes might be lost. I don't think "back to results" should even be an option if any unsaved changes to the client's data have been made. Here is my proposal:
1. When editing an already existing client, the "back to results" button should only exist before the user has typed any changes into the form. Once s/he has entered any changes, "back to results" should be replaced by "revert changes". Now the user must either save their changes or revert back to the original data before they can leave the page (once they revert "back to results" can appear again).
2. When entering information on a brand-new client, "back to results" should never appear; neither should "revert changes" (because for a new client there is nothing to revert to). In place of these should be "cancel new client", which will drop any changes entered by the user and return them to the search page (maybe with a warning first).
3. The "save changes" button should always exist regardless of whether the form pertains to a new client or an old one, but it should only be active after the user has made some change to the form. When the user first arrives, or if the user enters self-canceling changes, "save changes" should be deactivated.

**Comment by cecilia-donnelly** [comment]
@nttaylor made this fix in e944bb0.
